from __future__ import annotations

import enum
from datetime import datetime
from uuid import uuid4

from sqlalchemy import DateTime, Enum, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, SoftDeleteMixin


class AlertStatus(str, enum.Enum):
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    CLOSED = "closed"
    FALSE_POSITIVE = "false_positive"


class AlertSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(Base, TimestampMixin, SoftDeleteMixin):
    """
    Security alert generated by the detection engine.
    Soft-deleted only — security evidence must be preserved.
    """

    __tablename__ = "alerts"

    id: Mapped[UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    tenant_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    rule_id: Mapped[UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("detection_rules.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    triggering_event_id: Mapped[UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("events.id", ondelete="SET NULL"),
        nullable=True,
    )
    status: Mapped[AlertStatus] = mapped_column(
        Enum(AlertStatus, name="alert_status_enum",
             values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=AlertStatus.OPEN,
        index=True,
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, name="alert_severity_enum",
             values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_host: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    assignee_id: Mapped[UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by_id: Mapped[UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_by_id: Mapped[UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    mitre_tactics: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    mitre_techniques: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    suppression_key: Mapped[str | None] = mapped_column(String(512), nullable=True, index=True)
    ai_metadata: Mapped[dict | None] = mapped_column("metadata", JSONB, nullable=True, default=None)

    @property
    def ai_analysis(self) -> dict | None:
        if self.ai_metadata is None:
            return None
        return self.ai_metadata.get("ai_analysis")

    # ── Evidence-derived convenience properties ───────────────────────────────

    @property
    def rule_name(self) -> str | None:
        ev = self.evidence or {}
        name = ev.get("rule_name")
        if name:
            return name
        # Fall back: extract rule name from title ("Rule Name — on Host by proc (user)")
        title = self.title or ""
        em_dash_pos = title.find(" — ")
        return title[:em_dash_pos] if em_dash_pos > 0 else title

    @property
    def username(self) -> str | None:
        ev = self.evidence or {}
        user = ev.get("user") or {}
        return user.get("name") or user.get("username") or None

    @property
    def source_ip(self) -> str | None:
        ev = self.evidence or {}
        network = ev.get("network") or {}
        return network.get("src_ip") or None

    @property
    def raw_event_count(self) -> int:
        ev = self.evidence or {}
        return int(ev.get("threshold_count") or 1)

    @property
    def first_seen_at(self) -> datetime | None:
        ev = self.evidence or {}
        ts = ev.get("event_timestamp")
        if ts:
            try:
                return datetime.fromisoformat(ts)
            except (ValueError, TypeError):
                pass
        return self.created_at

    @property
    def last_seen_at(self) -> datetime | None:
        return self.updated_at or self.created_at

    @property
    def assignee_name(self) -> str | None:
        return None  # populated via join in endpoints that need it

    __table_args__ = (
        Index("idx_alert_tenant_status", "tenant_id", "status"),
        Index("idx_alert_tenant_severity", "tenant_id", "severity"),
        Index("idx_alert_tenant_created", "tenant_id", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Alert id={self.id} title={self.title!r} status={self.status}>"
