import { BookOpen, Plus, Shield, Zap, Brain } from "lucide-react";

const RULE_CATEGORIES = [
  {
    icon: Shield,
    color: "rgba(248,113,113,0.1)",
    borderColor: "rgba(248,113,113,0.2)",
    iconColor: "#F87171",
    title: "Signature Rules",
    count: 0,
    desc: "Static pattern matching rules based on known IOCs and attack signatures.",
  },
  {
    icon: Zap,
    color: "rgba(251,191,36,0.08)",
    borderColor: "rgba(251,191,36,0.2)",
    iconColor: "#FBBF24",
    title: "Behavioral Rules",
    count: 0,
    desc: "Anomaly detection rules that model normal behavior and flag deviations.",
  },
  {
    icon: Brain,
    color: "rgba(139,92,246,0.1)",
    borderColor: "rgba(139,92,246,0.2)",
    iconColor: "#A78BFA",
    title: "AI-Generated Rules",
    count: 0,
    desc: "Rules automatically generated by NEURASHIELD from threat intelligence feeds.",
  },
];

export function RulesPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="page-title">Detection Rules</h1>
          <p className="text-sm text-text-muted mt-1">Manage and tune your detection logic</p>
        </div>
        <button className="btn-primary text-sm">
          <Plus className="w-4 h-4" />
          New Rule
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {RULE_CATEGORIES.map((cat) => (
          <div
            key={cat.title}
            className="rounded-2xl p-6 border transition-all hover:border-opacity-50"
            style={{
              background: cat.color,
              border: `1px solid ${cat.borderColor}`,
            }}
          >
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center mb-4"
              style={{ background: "rgba(0,0,0,0.3)", border: `1px solid ${cat.borderColor}` }}
            >
              <cat.icon className="w-5 h-5" style={{ color: cat.iconColor }} />
            </div>
            <p className="font-display font-semibold text-text-primary mb-1">{cat.title}</p>
            <p className="text-2xl font-bold tabular-nums mb-2" style={{ color: cat.iconColor }}>
              {cat.count}
            </p>
            <p className="text-xs text-text-muted leading-relaxed">{cat.desc}</p>
          </div>
        ))}
      </div>

      <div
        className="rounded-2xl p-12 flex flex-col items-center justify-center text-center border"
        style={{
          background: "rgba(8,8,16,0.6)",
          borderColor: "rgba(139,92,246,0.15)",
          borderStyle: "dashed",
        }}
      >
        <div
          className="w-14 h-14 rounded-2xl flex items-center justify-center mb-4"
          style={{ background: "rgba(139,92,246,0.1)", border: "1px solid rgba(139,92,246,0.2)" }}
        >
          <BookOpen className="w-6 h-6 text-neural-400" />
        </div>
        <h2 className="font-display text-lg font-semibold text-text-primary mb-2">
          No Rules Configured
        </h2>
        <p className="text-sm text-text-muted max-w-md leading-relaxed mb-6">
          Import SIGMA rules, write custom detection logic, or let NEURASHIELD
          auto-generate rules from threat intelligence.
        </p>
        <div className="flex items-center gap-3">
          <button className="btn-primary text-sm">
            <Plus className="w-4 h-4" />
            Create Rule
          </button>
          <button className="btn-secondary text-sm">
            Import SIGMA
          </button>
        </div>
      </div>
    </div>
  );
}
